/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    HelloWord: typeof import('./src/pages/HelloWord.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Window: typeof import('./src/components/Window.vue')['default']
  }
}
